name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --needed \
            make git \
            mingw-w64-x86_64-toolchain \
            mingw-w64-x86_64-autotools
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: |
          NAME=oncrpc-ms-g`git rev-parse --short HEAD`
          mkdir $NAME
          make install DESTDIR=`pwd`/$NAME
          tar -acf $NAME.tar.xz $NAME
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/oncrpc-ms-*.tar.xz
